ephemeral_ephemeral-kube-sameera-2025-12-09-1_app_74afe68_ephemeral_env.yaml Created

diff --git a/.github/workflows/ephemeral_ephemeral-kube-sameera-2025-12-09-1_app_74afe68_ephemeral_env.yaml b/.github/workflows/ephemeral_ephemeral-kube-sameera-2025-12-09-1_app_74afe68_ephemeral_env.yaml
--- a/.github/workflows/ephemeral_ephemeral-kube-sameera-2025-12-09-1_app_74afe68_ephemeral_env.yaml
+++ b/.github/workflows/ephemeral_ephemeral-kube-sameera-2025-12-09-1_app_74afe68_ephemeral_env.yaml
@@ -5,9 +5,16 @@ name: >-
   push:
     branches:
       - main
+    tags:
+      - v*
+    paths-ignore:
+      - .github/workflows/**
+      - .trivyignore
+      - Readme.md
+      - README.md
   workflow_dispatch: {}
   repository_dispatch:
-    types: pipeline_5a14e459-5218-4459-bf2f-a5cd166c19a0
+    types: pipeline_ab5402cb-96fc-4992-a45a-54c5ad99c247
 env:
   ENCODED_PIPELINE_SECRET: >-
     ${{secrets.LAMBDADOCKERTEST_EPHEMERAL_EPHEMERALKUBESAMEERA202512091_APP_74AFE68_EPHEMERAL_ENV}}
@@ -15,6 +22,7 @@ env:
   BRANCH_NAME: >-
     ${{github.event.client_payload.branchName || github.event.branch ||
     github.ref_name}}
+  DEPLOY_STEP_SHOULD_DEPLOY: 'true'
 jobs:
   code-scan:
     name: Code Scan
@@ -840,7 +848,38 @@ jobs:
                 echo "Skipping checkout..."
               fi
             
-      - name: EPHEMERAL_DEPLOY
+      - name: 'Run :: Ephemeral Deploy and Notify Resource Service'
+        env:
+          RUN_ID: ${{ github.run_id }}
+          COMMIT_USER: ${{ github.event.head_commit.author.name }}
+          COMMIT_TIME: ${{ github.event.head_commit.timestamp }}
+          COMMIT_MESSAGE: >-
+            ${{ github.event.head_commit.message ||
+            github.event.client_payload.commitMessage }}
+        run: |2-
+
+              if [ -z "$COMMIT_MESSAGE" ]; then
+                COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr '\n' ' ')
+                echo "Fetched commit message: $COMMIT_MESSAGE"
+                echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
+              fi
+            
+              response=$(curl -X PATCH -d "imageRegistryURL=${{ env.IMAGE_NAME }}&appVersionId=${{ env.DEPLOYMENT_APP_VERSION_ID }}&tag=${{ env.COMMIT_ID }}&containerName=${{ env.DEPLOYMENT_CONTAINER_NAME }}&shouldDeploy=${{env.DEPLOY_STEP_SHOULD_DEPLOY}}&pipelineRunId=${{ env.RUN_ID }}&commitDetails[commitHash]=${{ env.COMMIT_ID }}&commitDetails[commitAvatar]=https://github.com/$COMMIT_USER.png&commitDetails[commitTime]=$COMMIT_TIME&commitDetails[commitMessage]=$COMMIT_MESSAGE&commitDetails[commitUser]=$COMMIT_USER"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-application-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  "${{ env.DEPLOYMENT_ENDPOINT }}")
+              
+              status_code=$?
+
+              if [ $status_code -eq 0 ]; then
+                if echo "$response" | grep -q '"success":true'; then
+                  echo "SUCCESS :: $response"
+                else
+                  echo "FAILED :: $response"
+                  exit 1
+                fi
+              else
+                echo "Failed to deploy. HTTP status code: $status_code"
+                exit 1
+              fi
+            
     needs:
       - build-and-push
       - _status_testing
