test_container-staging_app_0ce07a7_env_7c0e88c.yaml Updated

diff --git a/.github/workflows/test_container-staging_app_0ce07a7_env_7c0e88c.yaml b/.github/workflows/test_container-staging_app_0ce07a7_env_7c0e88c.yaml
--- a/.github/workflows/test_container-staging_app_0ce07a7_env_7c0e88c.yaml
+++ b/.github/workflows/test_container-staging_app_0ce07a7_env_7c0e88c.yaml
@@ -755,6 +755,47 @@ jobs:
                 echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                 
       - name: 'Run :: Deploy and Notify Resource Service'
+        run: |2-
+
+                if [ -z "$COMMIT_MESSAGE" ]; then
+                  COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr '\n' ' ')
+                  echo "Fetched commit message: $COMMIT_MESSAGE"
+                  echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
+                fi
+              
+                DEPLOY_COMMIT_HASH=""
+                # Read merged commit ID from artifact if it exists
+                if [[ -f ./artifact/commit_id.txt && -s ./artifact/commit_id.txt ]]; then
+                  DEPLOY_COMMIT_HASH=$(< ./artifact/commit_id.txt)
+                  echo "Merged commit ID found: $DEPLOY_COMMIT_HASH"
+                else
+                  DEPLOY_COMMIT_HASH="$COMMIT_ID"
+                  echo "No merged commit ID found. Using COMMIT_ID from environment: $DEPLOY_COMMIT_HASH"
+                fi
+                
+                response=$(curl -X PATCH -d "imageRegistryURL=${{ env.IMAGE_NAME }}&appVersionId=${{ env.DEPLOYMENT_APP_VERSION_ID }}&tag=$DEPLOY_COMMIT_HASH&containerName=${{ env.DEPLOYMENT_CONTAINER_NAME }}&shouldDeploy=${{env.DEPLOY_STEP_SHOULD_DEPLOY}}&pipelineRunId=$RUN_ID&commitDetails[commitHash]=$DEPLOY_COMMIT_HASH&commitDetails[commitAvatar]=https://github.com/$COMMIT_USER.png&commitDetails[commitTime]=$COMMIT_TIME&commitDetails[commitMessage]=$COMMIT_MESSAGE&commitDetails[commitUser]=$COMMIT_USER"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-application-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  "${{ env.DEPLOYMENT_ENDPOINT }}")
+                
+                status_code=$?
+
+                if [ $status_code -eq 0 ]; then
+                  if echo "$response" | grep -q '"success":true'; then
+                    echo "SUCCESS :: $response"
+                  else
+                    echo "FAILED :: $response"
+                    exit 1
+                  fi
+                else
+                  echo "Failed to deploy. HTTP status code: $status_code"
+                  exit 1
+                fi
+        env:
+          RUN_ID: ${{ github.run_id }}
+          COMMIT_USER: ${{ github.event.head_commit.author.name }}
+          COMMIT_TIME: ${{ github.event.head_commit.timestamp }}
+          COMMIT_MESSAGE: >-
+            ${{ env.MERGE_COMMIT_MESSAGE || github.event.head_commit.message ||
+            github.event.client_payload.commitMessage }}
+      - name: 'Run :: Deploy and Notify Resource Service'
         env:
           RUN_ID: ${{ github.run_id }}
           COMMIT_USER: ${{ github.event.head_commit.author.name }}
